return {
  -- {
  --   "mason-org/mason.nvim",
  --   opts = {
  --     registries = {
  --       "github:mason-org/mason-registry",
  --       "github:Crashdummyy/mason-registry",
  --     },
  --     ensure_installed = {
  --       "shellcheck",
  --       "shfmt",
  --       "flake8",
  --
  --       "lua-language-server",
  --
  --       "xmlformatter",
  --       "csharpier",
  --       "prettier",
  --
  --       "stylua",
  --       "bicep-lsp",
  --       "html-lsp",
  --       "css-lsp",
  --       "eslint-lsp",
  --       "typescript-language-server",
  --       "json-lsp",
  --
  --       "roslyn",
  --
  --       "tree-sitter-cli",
  --     },
  --   },
  -- },
}
